-- Shared 010d3 startup and preflight inventory; exact compatibility definitions.
SELECT COALESCE(
 (SELECT bool_and(to_regclass('public.'||name) IS NOT NULL) FROM (VALUES
 ('migration_admitted_history_root'),
 ('migration_admitted_history_plan'),
 ('migration_admitted_history_attempt'),
 ('migration_admitted_history_manifest'),
 ('migration_admitted_history_candidate'),
 ('migration_admitted_history_result'),
 ('migration_admitted_history_remainder'),
 ('migration_admitted_history_receipt'),
 ('migration_admitted_history_reservation'),
 ('migration_admitted_history_issue')) required(name))
 AND (SELECT bool_and(EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.'||signature) AND md5(p.prosrc)=body_md5)) FROM (VALUES
 ('crm_workspace_shared(uuid)','5935cf5ffc9c1d2dfddf67bc62c2b76f'),
 ('crm_history_complete_read(uuid)','25e6ede2e38e4ff4c34979bb1bf68658'),
 ('crm_admitted_history_write_fence()','204dca1fab619a05f1f7fc25cc635c3c'),
 ('crm_admitted_history_retained_size(jsonb)','2e016c5394e55a47bdc780b9c98dc73b'),
 ('crm_admitted_history_measure()','8f443cb578e5bb3ce9bc345d90b77853'),
 ('crm_history_import_measure()','9e5b10663974a2821f42f59763e3ef41'),
 ('crm_admitted_history_immutable()','53c389083f98cafa28f61cb95b80c66e'),
 ('crm_admitted_history_fact_allowed(jsonb,text)','f34dfe142392ca870e283a92b821a997'),
 ('crm_admitted_history_owner_insert()','7cc1d0fccd05e9913d74618888ce0134'),
 ('crm_admitted_history_evidence_insert()','524c22d91630b44a1ac4aee8c2a86d05'),
 ('crm_admitted_history_result_insert()','c11ab03eeb52c8e908b2c7665db7c908'),
 ('crm_admitted_history_suppress()','f3f7b10160bd0f3cc0d03fa2d75c9084'),
 ('crm_admitted_history_person_erasure()','56022e04f80c7fea6882a910b408ba36'),
 ('crm_admitted_history_identity_erasure()','2880bdc161c8ead5621a1738034817bb'),
 ('crm_history_display_owner_immutable()','d394174718cb248c64598ff2277fc2f9')) expected(signature,body_md5))
 AND (SELECT bool_and(EXISTS(SELECT 1 FROM pg_constraint c WHERE c.conrelid=to_regclass('public.'||name) AND c.contype='c' AND c.convalidated AND pg_get_constraintdef(c.oid) LIKE '%admitted_root_id%')) FROM (VALUES ('migration_history_import_identity'),('migration_history_import_display'),('fub_event_record_imported'),('fub_call_record_imported'),('fub_text_record_imported')) owners(name))
 AND (SELECT bool_and(EXISTS(SELECT 1 FROM pg_trigger t WHERE t.tgrelid=to_regclass('public.'||name) AND t.tgfoid=to_regprocedure('public.crm_admitted_history_write_fence()') AND t.tgenabled IN ('O','A') AND t.tgtype=31)) FROM (VALUES
 ('migration_admitted_history_root'),
 ('migration_admitted_history_plan'),
 ('migration_admitted_history_attempt'),
 ('migration_admitted_history_manifest'),
 ('migration_admitted_history_candidate'),
 ('migration_admitted_history_result'),
 ('migration_admitted_history_remainder'),
 ('migration_admitted_history_receipt'),
 ('migration_admitted_history_reservation'),
 ('migration_admitted_history_issue'),
 ('migration_history_import_run'),
 ('migration_history_import_plan'),
 ('migration_history_import_manifest'),
 ('migration_history_import_candidate'),
 ('migration_history_import_stream'),
 ('migration_history_import_identity'),
 ('migration_history_import_display'),
 ('migration_history_import_result'),
 ('migration_history_import_receipt'),
 ('migration_history_import_reservation'),
 ('fub_event_record_imported'),
 ('fub_call_record_imported'),
 ('fub_text_record_imported')) fenced(name))
 AND (SELECT bool_and(EXISTS(SELECT 1 FROM pg_trigger t WHERE t.tgrelid=to_regclass('public.'||name) AND t.tgfoid=to_regprocedure('public.'||signature) AND t.tgenabled IN ('O','A') AND t.tgtype=expected_type)) FROM (VALUES
 ('migration_admitted_history_root','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_plan','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_attempt','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_manifest','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_candidate','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_issue','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_result','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_remainder','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_receipt','crm_admitted_history_immutable()',27),
 ('migration_admitted_history_root','crm_admitted_history_measure()',29),
 ('migration_admitted_history_plan','crm_admitted_history_measure()',29),
 ('migration_admitted_history_manifest','crm_admitted_history_measure()',29),
 ('migration_admitted_history_candidate','crm_admitted_history_measure()',29),
 ('migration_admitted_history_issue','crm_admitted_history_measure()',29),
 ('migration_admitted_history_receipt','crm_admitted_history_measure()',29),
 ('migration_admitted_history_result','crm_admitted_history_measure()',29),
 ('migration_admitted_history_remainder','crm_admitted_history_measure()',29),
 ('migration_admitted_history_manifest','crm_admitted_history_evidence_insert()',7),
 ('migration_admitted_history_candidate','crm_admitted_history_evidence_insert()',7),
 ('migration_admitted_history_issue','crm_admitted_history_evidence_insert()',7),
 ('migration_history_import_identity','crm_admitted_history_owner_insert()',7),
 ('migration_history_import_display','crm_admitted_history_owner_insert()',7),
 ('migration_admitted_history_result','crm_admitted_history_result_insert()',7),
 ('migration_history_import_display','crm_admitted_history_suppress()',9),
 ('migration_history_import_identity','crm_admitted_history_identity_erasure()',17),
 ('migration_history_import_display','crm_history_display_owner_immutable()',19),
 ('person','crm_admitted_history_person_erasure()',11)) guarded(name,signature,expected_type))
 AND (SELECT bool_and(has_table_privilege('crm_app',to_regclass('public.'||name),'SELECT,INSERT')) FROM (VALUES
 ('migration_admitted_history_root'),
 ('migration_admitted_history_plan'),
 ('migration_admitted_history_attempt'),
 ('migration_admitted_history_manifest'),
 ('migration_admitted_history_candidate'),
 ('migration_admitted_history_result'),
 ('migration_admitted_history_remainder'),
 ('migration_admitted_history_receipt'),
 ('migration_admitted_history_reservation'),
 ('migration_admitted_history_issue')) readable(name))
 ,false)
