import { flushPromises, mount, RouterLinkStub } from '@vue/test-utils'
import { QueryClient, VueQueryPlugin } from '@tanstack/vue-query'
import PrimeVue from 'primevue/config'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ApiError, apiFetch } from '../../api/client'
import { queryKeys } from '../../api/queries'
import { resetWorkspace } from '../../workspaceLifecycle'
import PeopleAdmissionPanel from './PeopleAdmissionPanel.vue'
vi.mock('../../api/client',async original=>({...await original<typeof import('../../api/client')>(),apiFetch:vi.fn()}))
const api=vi.mocked(apiFetch); const ROOT='/migrations/fub/people-admissions'; const REPORTS='/migrations/fub/core-change-reports'; const clean:Array<()=>void>=[]
const identity=(actor='actor',org='org',revision='2')=>({user:{id:actor,email:'a@test',display_name:'Admin'},organization:{id:org,name:'Org',role:'admin',workspace_mode:'migration_review',workspace_revision:revision},platform_admin:false})
const admission=(revision='2',expiry=new Date(Date.now()+600000).toISOString())=>({id:'run',parent_import_id:'parent',report_id:'report',state:'ready',lifecycle_revision:'4',created_at:'2026-09-13T00:00:00Z',updated_at:'2026-09-13T00:00:00Z',completed_at:null,pause_reason:null,newer_snapshot_id:'newer',newer_sequence:'9007199254740993123',retained_bytes:'3',reserved_bytes:'4',progress:{settled_items:'0'},plan:{id:'plan',revision,digest:'a'.repeat(64),expires_at:expiry,counts:{total:'3',eligible:'1',already_imported:'0',already_admitted:'0',excluded_original:'1',held:'1',intended_contacts:'56'}},actions:{confirm:true,repreview:true,retry:false,cancel:true}})
async function setup(handle?:(url:string,init?:RequestInit)=>unknown){const state={identity:identity(),run:admission()};const parent={id:'parent',state:'completed',confirmed_plan_id:'old',created_at:'2026-09-13T00:00:00Z'};api.mockImplementation(async(url,init)=>{const x=handle?.(url,init);if(x!==undefined)return await x as never;if(url==='/me')return state.identity as never;if(url==='/migrations/fub/imports?limit=20')return {imports:[parent],next_cursor:null} as never;if(url==='/migrations/fub/imports/parent')return parent as never;if(url===`${REPORTS}?parent_import_id=parent&limit=20`)return {reports:[{id:'report',parent_import_id:'parent',state:'completed',output_revision:'1',created_at:parent.created_at}],next_cursor:null} as never;if(url===`${ROOT}?parent_import_id=parent&limit=20`)return {items:[state.run],next_cursor:null} as never;if(url===`${ROOT}/run`)return state.run as never;if(url.startsWith(`${ROOT}/run/items?`))return {plan_id:'plan',plan_revision:state.run.plan.revision,items:[],next_cursor:null} as never;if(url.startsWith(`${ROOT}/run/results?`))return {results:[],next_cursor:null} as never;throw Error(`unexpected ${url}`)});const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const wrapper=mount(PeopleAdmissionPanel,{props:{refreshWorkspace:vi.fn()},global:{plugins:[[VueQueryPlugin,{queryClient:client}],[PrimeVue,{unstyled:true}]],stubs:{RouterLink:RouterLinkStub}},attachTo:document.body});clean.push(()=>{wrapper.unmount();client.clear()});await flushPromises();return {wrapper,client,state}}
function select(label:string){const l=[...document.querySelectorAll('label')].find(v=>v.textContent?.includes(label));return document.getElementById(l!.htmlFor) as HTMLSelectElement} async function choose(label:string,value:string){const e=select(label);e.value=value;e.dispatchEvent(new Event('change',{bubbles:true}));await flushPromises()} function button(text:string){return [...document.querySelectorAll('button')].find(v=>v.textContent?.trim()===text) as HTMLButtonElement} async function acks(){for(const v of document.querySelectorAll<HTMLInputElement>('input[type=checkbox]')){v.checked=true;v.dispatchEvent(new Event('change',{bubbles:true}))}await flushPromises()}
beforeEach(()=>{api.mockReset();resetWorkspace();vi.stubGlobal('crypto',{randomUUID:()=> 'fixed-request'})});afterEach(()=>{clean.splice(0).forEach(v=>v());document.body.innerHTML='';vi.unstubAllGlobals();resetWorkspace()})
describe('People admission component',()=>{
 it('replays an uncertain frozen confirmation byte-for-byte',async()=>{let n=0;await setup((url)=>url.endsWith('/confirm')?(++n===1?Promise.reject(new ApiError(0,'network_error')):{admission_id:'run',state:'queued'}):undefined);await choose('Completed parent import','parent');await choose('Saved People admission','run');await acks();button('Review exact admission').click();await flushPromises();button('Confirm admission').click();await flushPromises();expect(document.body.textContent).toContain('outcome is uncertain');button('Retry the same request').click();await flushPromises();const writes=api.mock.calls.filter(([,x])=>x?.method==='POST');expect(writes).toHaveLength(2);expect(writes[0]![1]?.body).toBe(writes[1]![1]?.body)})
 it('keeps an uncertain request through authority re-verification and purges it on identity change',async()=>{let reject!:(e:unknown)=>void;const pending=new Promise((_,no)=>{reject=no});const {client,state}=await setup((url)=>url.endsWith('/confirm')?pending:undefined);await choose('Completed parent import','parent');await choose('Saved People admission','run');await acks();button('Review exact admission').click();await flushPromises();button('Confirm admission').click();await flushPromises();state.identity=identity('actor','org','3');client.setQueryData(queryKeys.me,state.identity);reject(new ApiError(0,'network_error'));await flushPromises();expect(document.body.textContent).toContain('Retry the same request');state.identity=identity('new-actor','other','3');client.setQueryData(queryKeys.me,state.identity);await flushPromises();expect(document.body.textContent).not.toContain('Retry the same request')})
 it('resets acknowledgements when plan revision changes and expires reactively',async()=>{vi.useFakeTimers();const {state}=await setup();await choose('Completed parent import','parent');await choose('Saved People admission','run');await acks();expect(button('Review exact admission').disabled).toBe(false);state.run=admission('3',new Date(Date.now()+1000).toISOString());button('Reload admissions').click();await flushPromises();expect(button('Review exact admission').disabled).toBe(true);await acks();vi.advanceTimersByTime(2000);await flushPromises();expect(document.body.textContent).toContain('This preview expired');expect(button('Review exact admission').disabled).toBe(true);vi.useRealTimers()})
 it('drops a delayed prepare receipt after the report selection changes',async()=>{let resolve!:(v:unknown)=>void;const pending=new Promise<unknown>(yes=>{resolve=yes});await setup(url=>url===ROOT?pending:undefined);await choose('Completed parent import','parent');await choose('Completed report for newly observed People','report');button('Prepare admission preview').click();await flushPromises();await choose('Completed report for newly observed People','');resolve({admission_id:'late-private-run',state:'preparing'});await flushPromises();expect(document.body.textContent).not.toContain('late-private-run');expect(api.mock.calls.some(([url])=>url===`${ROOT}/late-private-run`)).toBe(false)})
 it('preserves opaque item cursors through a next page transition',async()=>{await setup(url=>url===`${ROOT}/run/items?plan_id=plan&limit=50`?{plan_id:'plan',plan_revision:'2',items:[],next_cursor:'opaque +/'}:url===`${ROOT}/run/items?plan_id=plan&cursor=opaque+%2B%2F&limit=50`?{plan_id:'plan',plan_revision:'2',items:[],next_cursor:null}:undefined);await choose('Completed parent import','parent');await choose('Saved People admission','run');await flushPromises();button('More admission items').click();await flushPromises();expect(api.mock.calls.some(([url])=>url===`${ROOT}/run/items?plan_id=plan&cursor=opaque+%2B%2F&limit=50`)).toBe(true)})
})
