//! Shared readiness rejects incomplete staged preparation before handover.
use crm_app::auth::workspace::ReleaseReadiness;
use sqlx::PgPool;

#[sqlx::test]
#[ignore]
async fn admitted_metadata_readiness_requires_complete_preparation_schema(pool: PgPool) {
    let release = ReleaseReadiness::for_tests();
    release
        .require_admitted_metadata(&mut pool.acquire().await.unwrap())
        .await
        .unwrap();
    for mutation in [
        "ALTER TABLE migration_people_admission DROP CONSTRAINT am_admission_root_key CASCADE",
        "ALTER TABLE migration_people_admission_result DROP CONSTRAINT am_admission_result_owner_key CASCADE",
        "ALTER TABLE migration_people_admission_result DROP CONSTRAINT am_admission_result_person_key CASCADE",
        "ALTER TABLE migration_snapshot DROP CONSTRAINT am_snapshot_account_key CASCADE",
        "ALTER TABLE migration_core_change_report DROP CONSTRAINT am_report_root_key CASCADE",
        "ALTER TABLE migration_core_change_report DROP CONSTRAINT am_report_plan_key CASCADE",
        "ALTER TABLE migration_metadata_import DROP CONSTRAINT am_original_account_key CASCADE",
        "ALTER TABLE migration_metadata_mapping DROP CONSTRAINT am_original_claim_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_cohort_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_admission_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_account_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_chain_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_successor_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_owner_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_owner_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_source DROP CONSTRAINT am_source_owner_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_result DROP CONSTRAINT am_result_owner_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_person_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_predecessor_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_claim_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_source_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_kind_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_source_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_cohort_source_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_remainder_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_evidence_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_result DROP CONSTRAINT am_result_kind_owner_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_admission_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_report_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_snapshot_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_predecessor_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_successor_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_root_chain_check CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP CONSTRAINT am_executor_org_fk CASCADE",
        "ALTER TABLE migration_metadata_catalog_readiness DROP CONSTRAINT am_readiness_actor_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_receipt DROP CONSTRAINT am_receipt_actor_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_root_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_report_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_remainder_plan_id_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT am_plan_evidence_plan_id_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_source DROP CONSTRAINT am_source_snapshot_owner_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_observation DROP CONSTRAINT am_observation_snapshot_owner_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_reservation DROP CONSTRAINT am_reservation_snapshot_owner_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_receipt DROP CONSTRAINT am_receipt_snapshot_owner_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_source DROP CONSTRAINT am_source_capture_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_observation DROP CONSTRAINT am_observation_source_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_observation DROP CONSTRAINT am_observation_record_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_alias DROP CONSTRAINT am_alias_source_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_root_admission_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_admission_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_expected_person_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_live_person_check CASCADE",
        "ALTER TABLE migration_admitted_metadata_operation DROP CONSTRAINT am_operation_manifest_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_result DROP CONSTRAINT am_result_manifest_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_result DROP CONSTRAINT am_result_person_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_result DROP CONSTRAINT am_result_mapping_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_result DROP CONSTRAINT am_result_unit_check CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_predecessor_check CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_base_plan_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_predecessor_check CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_base_plan_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP CONSTRAINT am_manifest_predecessor_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_predecessor_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_evidence_check CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_evidence_plan_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_source_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_dependency_fk CASCADE",
        "ALTER TABLE migration_metadata_catalog_claim DROP CONSTRAINT am_claim_owner_check CASCADE",
        "ALTER TABLE migration_metadata_catalog_claim DROP CONSTRAINT am_claim_original_mapping_fk CASCADE",
        "ALTER TABLE migration_metadata_catalog_claim DROP CONSTRAINT am_claim_original_account_fk CASCADE",
        "ALTER TABLE migration_metadata_catalog_claim DROP CONSTRAINT am_claim_admitted_mapping_fk CASCADE",
        "ALTER TABLE migration_metadata_catalog_claim DROP CONSTRAINT am_claim_admitted_account_fk CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_dependency_check CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN admission_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan ALTER COLUMN admission_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN parent_import_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan ALTER COLUMN parent_import_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN parent_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan ALTER COLUMN parent_plan_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN source_account_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan ALTER COLUMN source_account_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_source DROP COLUMN snapshot_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_source ALTER COLUMN snapshot_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_observation DROP COLUMN snapshot_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_observation ALTER COLUMN snapshot_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_manifest DROP COLUMN admission_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest ALTER COLUMN admission_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_manifest DROP COLUMN admission_item_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest ALTER COLUMN admission_item_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_manifest DROP COLUMN predecessor_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest ALTER COLUMN predecessor_plan_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN predecessor_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping ALTER COLUMN predecessor_plan_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN evidence_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping ALTER COLUMN evidence_plan_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN dependency_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping ALTER COLUMN dependency_plan_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN dependency_import_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping ALTER COLUMN dependency_import_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_receipt DROP COLUMN plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_receipt ALTER COLUMN plan_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_result DROP COLUMN mapping_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DISABLE TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_plan ENABLE REPLICA TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_source DISABLE TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_source ENABLE REPLICA TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_observation DISABLE TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_observation ENABLE REPLICA TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_manifest DISABLE TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_manifest ENABLE REPLICA TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_mapping DISABLE TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_mapping ENABLE REPLICA TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_receipt DISABLE TRIGGER admitted_metadata_owner_keys",
        "ALTER TABLE migration_admitted_metadata_receipt ENABLE REPLICA TRIGGER admitted_metadata_owner_keys",
        "DROP FUNCTION crm_admitted_metadata_owner_keys() CASCADE",
        "CREATE OR REPLACE FUNCTION crm_admitted_metadata_owner_keys() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;",
        "ALTER TABLE migration_admitted_metadata_operation DROP CONSTRAINT am_operation_manifest_fk; ALTER TABLE migration_admitted_metadata_operation ADD CONSTRAINT am_operation_manifest_fk FOREIGN KEY(manifest_id) REFERENCES migration_admitted_metadata_manifest(id)",
        "ALTER TABLE migration_admitted_metadata_operation DROP CONSTRAINT am_operation_manifest_fk; ALTER TABLE migration_admitted_metadata_operation ADD CONSTRAINT am_operation_manifest_fk FOREIGN KEY(manifest_id,plan_id,import_id,organization_id) REFERENCES migration_admitted_metadata_manifest(id,plan_id,import_id,organization_id) NOT VALID",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT am_mapping_dependency_check; ALTER TABLE migration_admitted_metadata_mapping ADD CONSTRAINT am_mapping_dependency_check CHECK(true)",
        "DROP INDEX am_admission_tag_source",
        "DROP INDEX am_admission_tag_source; CREATE INDEX am_admission_tag_source ON migration_people_admission_result(admission_id,organization_id,source_id) WHERE disposition='held'",
        "ALTER TABLE migration_admitted_metadata_result ALTER COLUMN mapping_id DROP EXPRESSION",
        "ALTER TABLE migration_admitted_metadata_manifest DROP COLUMN oversized CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest ALTER COLUMN oversized DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN field_name_key CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping ALTER COLUMN field_name_key SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT migration_admitted_metadata_mapping_field_name_key_check",
        "ALTER TABLE migration_admitted_metadata_mapping DROP CONSTRAINT migration_admitted_metadata_mapping_field_name_key_check; ALTER TABLE migration_admitted_metadata_mapping ADD CONSTRAINT migration_admitted_metadata_mapping_field_name_key_check CHECK(field_name_key IS NULL OR octet_length(field_name_key)=31)",
        "DROP INDEX migration_admitted_metadata_field_name",
        "DROP INDEX migration_admitted_metadata_field_name; CREATE INDEX migration_admitted_metadata_field_name ON migration_admitted_metadata_mapping(plan_id,organization_id,field_name_key,id)",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT migration_admitted_metadata_plan_preparation_phase_check; ALTER TABLE migration_admitted_metadata_plan ADD CONSTRAINT migration_admitted_metadata_plan_preparation_phase_check CHECK(preparation_phase IN ('sources','fields','options','tags','choices','cohort','values','seal','complete','remainder_mappings','remainder_people','remainder_operations'))",
        "DO $test$ DECLARE definition TEXT; BEGIN SELECT pg_get_functiondef('crm_admitted_metadata_preparation_bytes()'::regprocedure) INTO definition; EXECUTE replace(definition,'+COALESCE(octet_length(NEW.field_name_key),0)',''); END $test$;",
        "DO $test$ DECLARE definition TEXT; BEGIN SELECT pg_get_functiondef('crm_admitted_metadata_preparation_bytes()'::regprocedure) INTO definition; EXECUTE replace(definition,'+COALESCE(octet_length(OLD.field_name_key),0)',''); END $test$;",
        "DROP INDEX migration_admitted_metadata_mapping_parent",
        "DROP INDEX migration_admitted_metadata_plan_building",
        "DROP TABLE migration_admitted_metadata_observation",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN remainder_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN evidence_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan ALTER COLUMN remainder_plan_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN execute_unit CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping ALTER COLUMN execute_unit DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN dependency_result_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP COLUMN predecessor_manifest_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP COLUMN held_settled_people CASCADE",
        "DROP INDEX migration_admitted_metadata_mapping_predecessor",
        "DROP INDEX migration_admitted_metadata_manifest_predecessor",
        "DROP INDEX migration_admitted_metadata_mapping_execute",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT migration_admitted_metadata_plan_preparation_phase_check; ALTER TABLE migration_admitted_metadata_plan ADD CONSTRAINT migration_admitted_metadata_plan_preparation_phase_check CHECK(preparation_phase IN ('sources','fields','options','tags','choices','cohort','values','seal','complete'))",
        "DROP TABLE migration_admitted_metadata_alias",
        "ALTER TABLE migration_admitted_metadata_import DROP COLUMN admission_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_import ALTER COLUMN admission_plan_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_import DROP COLUMN settled_eligible_people CASCADE",
        "ALTER TABLE migration_admitted_metadata_import DROP COLUMN counts CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN dependent_count CASCADE",
        "ALTER TABLE migration_admitted_metadata_mapping DROP COLUMN alias_count CASCADE",
        "ALTER TABLE migration_admitted_metadata_alias DISABLE TRIGGER admitted_metadata_mapping_counts",
        "ALTER TABLE migration_admitted_metadata_operation ENABLE REPLICA TRIGGER admitted_metadata_mapping_counts",
        "DROP INDEX migration_admitted_metadata_alias_page",
        "DROP INDEX migration_admitted_metadata_result_filtered_page",
        "DROP INDEX migration_admitted_metadata_person_result_page",
        "DROP INDEX migration_admitted_metadata_cohort_seek",
        "DROP INDEX migration_admitted_metadata_one_root; CREATE UNIQUE INDEX migration_admitted_metadata_one_root ON migration_admitted_metadata_import(organization_id,admission_id) WHERE predecessor_import_id IS NULL",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN preparation_phase CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN preparation_bytes CASCADE",
        "ALTER TABLE migration_admitted_metadata_source DROP COLUMN qualified CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest DROP COLUMN expected_person_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_manifest ALTER COLUMN person_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_operation DISABLE TRIGGER admitted_metadata_preparation_bytes",
        "ALTER TABLE migration_admitted_metadata_operation ENABLE REPLICA TRIGGER admitted_metadata_preparation_bytes",
        "ALTER TABLE migration_metadata_identity ENABLE REPLICA TRIGGER migration_metadata_identity_claim_guard",
        "DROP INDEX migration_admitted_metadata_source_work",
        "DROP INDEX migration_admitted_metadata_source_order",
        "DROP INDEX migration_admitted_metadata_admission_work",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN snapshot_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN source_output_revision CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan DROP COLUMN previous_plan_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_plan ALTER COLUMN snapshot_id DROP NOT NULL",
        "ALTER TABLE migration_admitted_metadata_plan ALTER COLUMN previous_plan_id SET NOT NULL",
        "ALTER TABLE migration_admitted_metadata_receipt DROP COLUMN snapshot_id CASCADE",
        "ALTER TABLE migration_admitted_metadata_receipt ALTER COLUMN snapshot_id DROP NOT NULL",
        "DROP INDEX migration_admitted_metadata_selected_target",
        "DROP INDEX migration_admitted_metadata_mapping_prepare",
        "ALTER TABLE migration_admitted_metadata_plan DROP CONSTRAINT migration_admitted_metadata_plan_preparation_phase_check",
    ] {
        let mut tx = pool.begin().await.unwrap();
        sqlx::raw_sql(mutation).execute(&mut *tx).await.unwrap();
        let error = release
            .require_admitted_metadata(&mut tx)
            .await
            .expect_err(mutation);
        assert!(
            error
                .to_string()
                .contains("admitted metadata schema incompatible"),
            "{mutation}: {error}"
        );
        tx.rollback().await.unwrap();
    }
    release
        .require_admitted_metadata(&mut pool.acquire().await.unwrap())
        .await
        .unwrap();
}
